# Generated by Django 2.0.4 on 2018-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='Speakers')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('flag', models.BooleanField()),
            ],
        ),
    ]
