# Generated by Django 2.0.4 on 2018-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('details', models.TextField()),
                ('pic', models.ImageField(upload_to='Sponsors')),
                ('contact', models.IntegerField()),
                ('website', models.URLField(blank=True)),
                ('spons_type', models.TextField()),
                ('flag', models.BooleanField()),
            ],
        ),
    ]
